// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXamGmffYFhbHrX5h9ejut0Us3hyUgHGw',
    appId: '1:724715283419:web:4bfd1fd6271e2b2af37dfe',
    messagingSenderId: '724715283419',
    projectId: 'covid-app-2a0e3',
    authDomain: 'covid-app-2a0e3.firebaseapp.com',
    storageBucket: 'covid-app-2a0e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUN0dCPfoRhl_fldkk-RGr75oVQz98JTk',
    appId: '1:724715283419:android:8110d773dd125ef4f37dfe',
    messagingSenderId: '724715283419',
    projectId: 'covid-app-2a0e3',
    storageBucket: 'covid-app-2a0e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxJ-GPZh5WkC4xJUW9MbxCwY8aA4HyEVY',
    appId: '1:724715283419:ios:d275a1284279e1b4f37dfe',
    messagingSenderId: '724715283419',
    projectId: 'covid-app-2a0e3',
    storageBucket: 'covid-app-2a0e3.appspot.com',
    iosClientId: '724715283419-bp4tr55llq1fc7rgllfk40og8achpt3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.covidApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxJ-GPZh5WkC4xJUW9MbxCwY8aA4HyEVY',
    appId: '1:724715283419:ios:d275a1284279e1b4f37dfe',
    messagingSenderId: '724715283419',
    projectId: 'covid-app-2a0e3',
    storageBucket: 'covid-app-2a0e3.appspot.com',
    iosClientId: '724715283419-bp4tr55llq1fc7rgllfk40og8achpt3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.covidApp',
  );
}
